name: Sentiment Analysis CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas mlflow transformers evidently pytest
    - name: Run tests
      run: |
        pytest tests/test_pipeline.py
    - name: Run fix_predictions.py
      run: |
        python src/fix_predictions.py
    - name: Run monitor.py
      run: |
        python src/monitor.py
    - name: Archive report
      uses: actions/upload-artifact@v4
      with:
        name: sentiment_drift_report
        path: reports/sentiment_drift_report.html
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: \${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports